name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Integration Test
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./
        
